# version: '3.8'
name: inception

volumes:
  dbdata:
    driver: local
    driver_opts:
      type: none
      device: /home/lhojoon/Documents/dbdata
      o: bind
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /home/lhojoon/Documents/wordpress
      o: bind
networks:
  default:
    name: docker-network
    # external: true
services:
  mariadb:
    build: requirements/mariadb
    ports:
      - 3306:3306
    container_name: DB
    env_file:
      - .env
    tty: true
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - default
    restart: always
  nginx:
    build: requirements/nginx
    ports:
      - 443:443
    container_name: NGINX
    env_file:
      - .env
    tty: true
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/html
    networks:
      - default
    restart: always
    extra_hosts:
      - "lhojoon.42.fr:127.0.0.1"
  wordpress:
    build: requirements/wordpress
    ports:
      - 9000:9000
    container_name: Wordpress_PHP
    env_file: .env
    tty: true
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/html
    networks:
      - default
    restart: always