# version: '3.8'
name: inception

volumes:
  dbdata:
    driver: local
    driver_opts:
      type: none
      device: /home/lhojoon/dbdata
      o: bind
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /home/lhojoon/wordpress
      o: bind
networks:
  default:
    name: inception
    driver: bridge
services:
  mariadb:
    build: requirements/mariadb
    container_name: db_container
    env_file:
      - .env
    # tty: true
    volumes:
      # - dbdata:/var
      - dbdata:/var/lib/mysql
      # - dbdata:/var/log/mysql
    networks:
      - default
    ports:
      - 3306
    restart: always
  nginx:
    build: requirements/nginx
    ports:
      - 443:443
    container_name: NGINX_container
    env_file:
      - .env
    # tty: true
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/html/wordpress
    networks:
      - default
    restart: always
    extra_hosts:
      - "lhojoon.42.fr:127.0.0.1"
  wordpress:
    build: requirements/wordpress
    ports:
      - 9000
    container_name: Wordpress_PHP_container
    env_file: .env
    # tty: true
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/html/wordpress
    networks:
      - default
    restart: always